In [5]:
import pandas as pd
import numpy as np

In [7]:
#opening df
xls = pd.ExcelFile(r'C:\Users\aavil\Documents\codeop\Orangutanes\Registro orangutanes Barcelona.xlsx')
df_raw=pd.read_excel(xls,'Grupo')

In [8]:
df_raw

,Fecha,Sujeto,Periodo,Registro diario,Conducta,Receptor,Frecuencia,Duración,Ubicacion,Observaciones
0,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:15,vg2,NaN
1,2019-04-15,Karl,Prejuego,1.0,Forr,NaN,NaN,00:00:34,vg2,NaN
2,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:52,vg4,NaN
3,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:05,vg4,NaN
4,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:34,vg4,NaN
...,...,...,...,...,...,...,...,...,...,...
8109,2019-07-19,Hadia,Postjuego,2.0,Tre,NaN,NaN,00:00:09,pg4,NaN
8110,2019-07-19,Hadia,Postjuego,2.0,Alim,NaN,NaN,00:01:34,pg4,NaN
8111,2019-07-19,Hadia,Postjuego,2.0,Jacrob,NaN,NaN,00:00:21,pg4,NaN
8112,2019-07-19,Hadia,Postjuego,2.0,Bra,NaN,NaN,00:00:03,pg4,NaN
8113,2019-07-19,Hadia,Postjuego,2.0,Alim,NaN,NaN,00:03:12,pg3,NaN

In [9]:
#Removing "observaciones"
df1=df_raw.drop(labels="Observaciones", axis=1)

In [12]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df1['Sujeto'])
 
# printing label
label

array([2, 2, 2, ..., 0, 0, 0])

In [15]:
## Appending the array to our dataFrame
# with column name 'Purchased'
df1["Nuevo"] = label

In [23]:
#Checking number each subject
df1.loc[df1['Sujeto'] == "Popo"] #4
df1.loc[df1['Sujeto'] == "Hadia"] #0
df1.loc[df1['Sujeto'] == "Storma"] #5

,Fecha,Sujeto,Periodo,Registro diario,Conducta,Receptor,Frecuencia,Duración,Ubicacion,Nuevo
3075,2019-04-15,Storma,Prejuego,1.0,Jun,Locky,NaN,00.00:20,pp2,5
3076,2019-04-15,Storma,Prejuego,1.0,Alogroo,Locky,NaN,00:01:39,pp2,5
3077,2019-04-15,Storma,Prejuego,1.0,Jun,Locky,NaN,00:00:10,pp2,5
3078,2019-04-15,Storma,Prejuego,1.0,Jun,Locky Hadia,NaN,NaN,pp2,5
3079,2019-04-15,Storma,Prejuego,1.0,Roba,Hadia,NaN,00:00:10,pp2,5
...,...,...,...,...,...,...,...,...,...,...
4899,2019-07-19,Storma,Postjuego,2.0,Cam,NaN,NaN,00:00:03,vg2,5
4900,2019-07-19,Storma,Postjuego,2.0,Sen,NaN,NaN,00:01:00,vg4,5
4901,2019-07-19,Storma,Postjuego,2.0,Cam,NaN,NaN,00:00:05,pp1,5
4902,2019-07-19,Storma,Postjuego,2.0,Sen,NaN,NaN,00:00:42,pp1,5
4903,2019-07-19,Storma,Postjuego,2.0,Ins,NaN,NaN,00:00:10,pp1,5

In [17]:
df1["Nuevo"]

0       2
1       2
2       2
3       2
4       2
       ..
8109    0
8110    0
8111    0
8112    0
8113    0
Name: Nuevo, Length: 8114, dtype: int32