In [5]:
import pandas as pd
import numpy as np

In [7]:
#opening df
xls = pd.ExcelFile(r'C:\Users\aavil\Documents\codeop\Orangutanes\Registro orangutanes Barcelona.xlsx')
df_raw=pd.read_excel(xls,'Grupo')

In [8]:
df_raw

,Fecha,Sujeto,Periodo,Registro diario,Conducta,Receptor,Frecuencia,Duración,Ubicacion,Observaciones
0,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:15,vg2,NaN
1,2019-04-15,Karl,Prejuego,1.0,Forr,NaN,NaN,00:00:34,vg2,NaN
2,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:52,vg4,NaN
3,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:05,vg4,NaN
4,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:34,vg4,NaN
...,...,...,...,...,...,...,...,...,...,...
8109,2019-07-19,Hadia,Postjuego,2.0,Tre,NaN,NaN,00:00:09,pg4,NaN
8110,2019-07-19,Hadia,Postjuego,2.0,Alim,NaN,NaN,00:01:34,pg4,NaN
8111,2019-07-19,Hadia,Postjuego,2.0,Jacrob,NaN,NaN,00:00:21,pg4,NaN
8112,2019-07-19,Hadia,Postjuego,2.0,Bra,NaN,NaN,00:00:03,pg4,NaN
8113,2019-07-19,Hadia,Postjuego,2.0,Alim,NaN,NaN,00:03:12,pg3,NaN

In [9]:
#Removing "observaciones"
df1=df_raw.drop(labels="Observaciones", axis=1)

In [12]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df1['Sujeto'])
 
# printing label
label

array([2, 2, 2, ..., 0, 0, 0])

In [15]:
## Appending the array to our dataFrame
# with column name 'Purchased'
df1["Nuevo"] = label

In [26]:
#Checking number each subject
df1.loc[df1['Sujeto'] == "Popo"] #4
df1.loc[df1['Sujeto'] == "Hadia"] #0
df1.loc[df1['Sujeto'] == "Storma"] #5
df1.loc[df1['Sujeto'] == "Jawie"] #1
df1.loc[df1['Sujeto'] == "Locky"] #3
df1.loc[df1['Sujeto'] == "Karl"] #2

,Fecha,Sujeto,Periodo,Registro diario,Conducta,Receptor,Frecuencia,Duración,Ubicacion,Nuevo
0,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:15,vg2,2
1,2019-04-15,Karl,Prejuego,1.0,Forr,NaN,NaN,00:00:34,vg2,2
2,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:52,vg4,2
3,2019-04-15,Karl,Prejuego,1.0,Cam,NaN,NaN,00:00:05,vg4,2
4,2019-04-15,Karl,Prejuego,1.0,Sen,NaN,NaN,00:00:34,vg4,2
...,...,...,...,...,...,...,...,...,...,...
633,2019-07-19,Karl,Postjuego,2.0,Sen,NaN,NaN,00:01:27,pg2,2
634,2019-07-19,Karl,Postjuego,2.0,Cam,NaN,NaN,00:00:47,vg1,2
635,2019-07-19,Karl,Postjuego,2.0,Tre,NaN,NaN,00:00:03,vg1,2
636,2019-07-19,Karl,Postjuego,2.0,Cam,NaN,NaN,00:00:02,vg1,2
637,2019-07-19,Karl,Postjuego,2.0,Sen,NaN,NaN,00:02:45,vg1,2

In [17]:
df1["Nuevo"]

0       2
1       2
2       2
3       2
4       2
       ..
8109    0
8110    0
8111    0
8112    0
8113    0
Name: Nuevo, Length: 8114, dtype: int32